### ISSUE TITLE
无法正常使用自定义AI服务，如何修改配置文件

### ISSUE THREAD

**Issue by vimbackground** [lmk123/migpt-cli#31]
首先，没有看到issue的模板，还是这样先回复吧。

## 问题描述

不管是硅基流动、Mistral、Grok等，设置后，进行AI后，再对话，任何提问，音箱会回复“出错了”（后台设置的AI出错提示语）

这些api在其它AI客户端上都能正常工作。

请问是否接口地址的问题，比如我设置的xAI，接口地址设置成以下地址都报错

https://api.x.ai
https://api.x.ai/v1

## 硬件软件

- 硬件是小爱音箱pro
- 系统环境是黑群晖DSM 7.2.1-69057，
- docker环境是黑群套件Container  Manager 20.10.23-1437
- MIGPT是昨天通过ssh，在终端上运行“docker run -d --name migpt-server -p 36592:36592 lmk123/migpt-server”部署的最新版本

## 更多问题

如果需要手动设置migpt-server的提示词和相关配置，docker容器可以怎么设置，如目录如何映射。

**Comment by vimbackground** [comment]
错误日志文件如下：


 2024/11/13 08:07:38 Speaker ✅ 服务已启动...
 2024/11/13 08:07:43 Speaker 🔥 召唤一零
 2024/11/13 08:07:43 Speaker 🔊 你好，我是一零，需要我做什么吗？
 2024/11/13 08:07:57 Speaker 🔥 什么是大模型
 2024/11/13 08:07:57 Speaker 🔊 稍等
 2024/11/13 08:08:02 Open AI ❌ LLM 响应异常 BadRequestError: 400 status code (no body)
     at APIError.generate (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/error.mjs:41:20)
     at OpenAI.makeStatusError (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/core.mjs:282:25)
     at OpenAI.makeRequest (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/core.mjs:326:30)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async OpenAIClient.chatStream (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:1241:20) {
   status: 400,
   headers: {
     connection: 'close',
     'content-length': '87',
     'content-type': 'application/json; charset=utf-8',
     date: 'Wed, 13 Nov 2024 08:08:02 GMT'
   },
   request_id: undefined,
   error: undefined,
   code: undefined,
   param: undefined,
   type: undefined
 }
 2024/11/13 08:08:02 Open AI ❌ LLM 响应异常 BadRequestError: 400 status code (no body)
     at APIError.generate (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/error.mjs:41:20)
     at OpenAI.makeStatusError (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/core.mjs:282:25)
     at OpenAI.makeRequest (file:///usr/local/lib/node_modules/migpt-server/node_modules/openai/core.mjs:326:30)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async OpenAIClient.chat (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:1199:28)
     at async ShortTermMemoryAgent.generate (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:1968:17)
     at async MemoryManager._updateShortTermMemory (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:2068:23)
     at async MemoryManager.updateLongShortTermMemory (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:2045:21) {
   status: 400,
   headers: {
     connection: 'close',
     'content-length': '87',
     'content-type': 'application/json; charset=utf-8',
     date: 'Wed, 13 Nov 2024 08:08:02 GMT'
   },
   request_id: undefined,
   error: undefined,
   code: undefined,
   param: undefined,
   type: undefined
 }
 2024/11/13 08:08:02 Memory ❌ 💀 生成短期记忆失败
 2024/11/13 08:08:02 Speaker 🔊 唉~好像出错了
 
 
 / $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
 | $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
 | $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
 | $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
 | $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
 | $$\  $ | $$| $$| $$  \ $$| $$         | $$   
 | $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
 |__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                  
          MiGPT v4.2.0  by: del.wang
 
 
 2024/11/13 08:08:30 Speaker ✅ 服务已启动...
 
 
 / $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
 | $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
 | $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
 | $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
 | $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
 | $$\  $ | $$| $$| $$  \ $$| $$         | $$   
 | $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
 |__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                  
          MiGPT v4.2.0  by: del.wang
 
 
 2024/11/13 08:23:12 Speaker ✅ 服务已启动...
 端口： 36592
 登录认证： 未启用
 秘密路径： 已启用

**Comment by lmk123** [comment]
migpt 仅支持兼容 OpenAI 格式的大模型，我看了一下，gork 的接口格式是不兼容 openai 的，所以才会报错

**Comment by vimbackground** [comment]
我用硅基流动调用qwen，或者调用Mistral的api，也是不行，是不是也不完全兼容啊。

倒是在本地用lmstudio跑的qwen大模型，调用它的api时有反应。

但是后台显示上下文没有清除，前后干挠了，加上想自己修改一下基础提示词，不知道这个可不可以通过设置docker的映射，在配置目录里修改。

**Comment by lmk123** [comment]
我试了一下，我的硅基流动在 migpt 里是能正常调用的

docker 里的配置文件位置在这里 https://github.com/lmk123/migpt-cli/blob/main/docker/Dockerfile#L31

**Comment by vimbackground** [comment]
我又试了硅基流动，还是报错，请帮着看看附图，这个设置有什么问题吗？

![Snipaste_2024-11-13_19-43-32](https://github.com/user-attachments/assets/91574e1a-8033-40d8-9a88-edebae92adfb)

**Comment by lmk123** [comment]
模型名称没有复制完整

**Comment by lmk123** [comment]
https://migptgui.com/docs/apply/siliconflow

![image](https://github.com/user-attachments/assets/d56fa147-2fed-42fb-94eb-5081a7b7df92)
